### ISSUE TITLE
Please publish to PyPI

### ISSUE THREAD

**Issue by Miserlou** [icholy/durationpy#1]
This is a useful library, especially because Go uses this same format.

It'd be great if you could please publish this to PyPI to make it `pip` installable!

**Comment by icholy** [comment]
I've never done this before. Gotta lookup how to do it.

**Comment by Miserlou** [comment]
This is a pretty good guide, but could do with a TL;DR. https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html#quick-start

**Comment by icholy** [comment]
https://pypi.python.org/pypi/durationpy

**Comment by Miserlou** [comment]
Hooray!

**Comment by Miserlou** [comment]
Oh, so, this didn't actually work - I think maybe you forgot to include the code? 

Annoyingly, this might mean you need to add a `MANIFEST.in` file to describe where your code is.

**Comment by icholy** [comment]
whoops

**Comment by icholy** [comment]
@Miserlou try it now.
