### ISSUE TITLE
Potentially invalid escape sequence

### ISSUE THREAD

**Issue by federicotdn** [icholy/durationpy#14]
Hi, when using this library under Python 3.12, I am getting the following warning:

```
/opt/project-venv/lib/python3.12/site-packages/durationpy/duration.py:39: SyntaxWarning: invalid escape sequence '\d'
  pattern = re.compile('([\d\.]+)([a-zµμ]+)')
```
Maybe worth looking into.

**Comment by icholy** [comment]
Not sure how you're getting that error because that line should be a raw string:

``` python
pattern = re.compile(r'([\d\.]+)([a-zµμ]+)')
```

**Comment by federicotdn** [comment]
Sorry, it looks like the version we were using is much older than I thought. All good!
