### ISSUE TITLE
Add support for 'd', 'mm', 'y'

### ISSUE THREAD

**Issue by Miserlou** [icholy/durationpy#3]
Go doesn't allow these values, but we're not bound by their restrictions.

Even if they're not available by default, it'd be useful to allow these values for our purposes.

**Comment by Miserlou** [comment]
1 day = 24h, 1mm = 30d, 1y = 365

No need for any further precision than that, IMO.

**Comment by icholy** [comment]
I have code that depends on it being compatible with Go's format. I'd be open to adding some additional methods with this behaviour. Do you have a preference on the naming?

**Comment by Miserlou** [comment]
Just what I stated on the naming.

I think Go-compatibility is probably the most useful by default, but perhaps these be enabled by setting `extended=True` to the API. 

Alternate ideas could be `go_compatible=False`, or a dict of allowed values and what they map to, so I could `extra_tokens={'mm': 31}`.

**Comment by icholy** [comment]
I just pushed some code to master. Thoughts?
``` py
durationpy.to_str(ts, extended=True)
```

**Comment by Miserlou** [comment]
I like it!

**Comment by icholy** [comment]
tagged and published.

**Comment by Miserlou** [comment]
Sweet!

**Comment by Miserlou** [comment]
Any chance we can get this added to `from_str` as well? :)

**Comment by icholy** [comment]
@Miserlou should already work.

**Comment by Miserlou** [comment]
Oooh, ok.
