### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by Miserlou** [icholy/durationpy#4]
Turns out this doesn't work with P3. :[

Should be a 1 character change, change `from duration` to `from .duration`

**Comment by icholy** [comment]
Is that backwards compatible?

**Comment by Miserlou** [comment]
Should be: http://python-future.org/compatible_idioms.html#imports-relative-to-a-package

**Comment by icholy** [comment]
PR?

**Comment by Miserlou** [comment]
PR opened: https://github.com/icholy/durationpy/pull/5
